# Generated by Django 3.0.5 on 2020-05-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=75)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
    ]
